package org.fao.fenix.web.modules.dataviewer.common.enums;

import com.google.gwt.user.client.rpc.IsSerializable;

public enum DataViewerBoxContent implements IsSerializable {
	
	// Outputs
	CHART,
	BAR, PIE, TIMESERIE, SCATTER, BAR_WITH_CATEGORIES, AREA, STACKED,
	
	HTML,
	
	MAP,
	MAP_GOOGLE,
	TABLE,
	PIVOT_TABLE,
	FENIX_METADATA_TABLE, 
	FAOSTAT_METADATA_TABLE, 
	METADATA_METHODOLOGY,
	DOMAIN_NOTES,
	DOMAIN_NOTES_CONTENT,
	
	// Exports
	EXPORT,
	EXPORT_CSV, EXPORT_EXCEL,
	EXPORT_EXCEL_VALUES,
	TO_EXPORT,
	
	// Retrieving Informations
	GET,
	CODING_SYSTEM_FAOSTAT_ALL_GROUPS_DOMAINS, 
	CODING_SYSTEM_FAOSTAT_GROUPS,
	CODING_SYSTEM_FAOSTAT_DOMAINS_FOR_GROUP,
	CODING_SYSTEM_FAOSTAT_ELEMENT,
	CODING_SYSTEM_FAOSTAT_ELEMENT_LIST,
	CODING_SYSTEM_FAOSTAT_ELEMENT_BY_DOMAIN_ITEM_ELEMENT,
	CODING_SYSTEM_FAOSTAT_ITEM,
	CODING_SYSTEM_FAOSTAT_ITEM_COMPARE,
	CODING_SYSTEM_FAOSTAT_ITEM_AGGREGATIONS,
	CODING_SYSTEM_FAOSTAT_ITEM_DISAGGREGATIONS,
	CODING_SYSTEM_FAOSTAT_ITEM_BY_DOMAIN_ITEM_ELEMENT,
	CODING_SYSTEM_FAOSTAT_ITEM_BY_DOMAIN_ITEM_ELEMENT_UNIT,
	CODING_SYSTEM_FAOSTAT_COUNTRIES,
	CODING_SYSTEM_FAOSTAT_AREAS_WORLD,
	CODING_SYSTEM_FAOSTAT_AREAS_WORLD_AGGREGATED,
	CODING_SYSTEM_FAOSTAT_AREAS_FAO,
	CODING_SYSTEM_FAOSTAT_COUNTRIES_AREAS_ALL,
	CODING_SYSTEM_FAOSTAT_YEAR,
	CODING_SYSTEM_FAOSTAT_COUNTRIES_CONTINENTS,
	CODING_SYSTEM_FAOSTAT_ALL_METADATA_GROUPS_DOMAINS,
	CODING_SYSTEM_FAOSTAT_ALL_GROUPS_DOMAINS_BULK_DOWNLOAD,
	CODING_SYSTEM_FAOSTAT_ALL_METADATA_METHODOLOGIES,
	
	// used for the search (i.e. GET + ITEMS_BY_LABEL) 
	ITEMS_BY_LABEL,
	ELEMENTS_BY_LABEL,
	GROUPS_AND_DOMAINS_BY_ITEM,
	GROUPS_AND_DOMAINS_BY_ELEMENTLIST,
	RESULT_SEARCH_INFOS,
	RESULT_SEARCH_ITEMS,
	RESULT_SEARCH_ELEMENTS,
	
	SEARCH_BY_ITEM,
	SEARCH_BY_ELEMENT,
	
		
	CODING_SYSTEM_FAOSTAT_DOMAINS_FROM_FENIX, 
	
	// WEBAPPS
	R_GWT,
	
	//Image Size
	SMALL_SIZE, MEDIUM_SIZE, LARGE_SIZE,
	
	// Items for "DOWNLOAD"
	DOWNLOAD_GET_ITEMS_AND_AGGREGATES,
	DOWNLOAD_GET_ITEMS_ONLY,
	DOWNLOAD_GET_AGGREGATES_ONLY;
	
}
