package org.fao.fenix.web.modules.core.client.utils;

import java.util.ArrayList;

import com.google.gwt.user.client.ui.ListBox;

/**
 * @deprecated use a centralized class, with gaul codes + labels loaded from db.
 */
@Deprecated
public class DataUtils {

	private ArrayList list;
	
	/**
	 * @deprecated use a centralized class, with gaul codes + labels loaded from db.
	 */
	@Deprecated
	public DataUtils() {
		list = new ArrayList();
	}
	
	// project list as per GW2.3 
	/**
	 * @deprecated use a centralized class, with gaul codes + labels loaded from db.
	 */
	@Deprecated
	public String[] countries = new String[] { 
			"Afghanistan",
			"Albania",
			"Algeria",
			"Andorra",
			"Angola",
			"Anguilla",
			"Antigua and Barbuda",
			"Argentina",
			"Armenia",
			"Australia",
			"Austria",
			"Azerbaijan",
			"Bahamas",
			"Bahrain",
			"Bangladesh",
			"Barbados",
			"Belarus",
			"Belgium",
			"Belize",
			"Benin",
			"Bhutan",
			"Bolivia",
			"Bosnia and Herzegovina",
			"Botswana",
			"Brazil",
			"British Virgin Islands",
			"Bulgaria",
			"Burkina Faso",
			"Burundi",
			"Cambodia",
			"Cameroon",
			"Canada",
			"Cape Verde",
			"Central African Republic",
			"Chad",
			"Chile",
			"China",
			"Colombia",
			"Comoros",
			"Congo",
			"Cook Islands",
			"Costa Rica",
			"Croatia",
			"Cuba",
			"Cyprus",
			"Czech Republic",
			"Cote d'Ivoire",
			"Dem People's Rep of Korea",
			"Democratic Republic of the Congo",
			"Denmark",
			"Djibouti",
			"Dominica",
			"Dominican Republic",
			"Ecuador",
			"Egypt",
			"El Salvador",
			"Equatorial Guinea",
			"Eritrea",
			"Estonia",
			"Ethiopia",
			"Fiji",
			"Finland",
			"France",
			"French Guiana",
			"French Polynesia",
			"Gabon",
			"Gambia",
			"Georgia",
			"Germany",
			"Ghana",
			"Greece",
			"Grenada",
			"Guadeloupe",
			"Guatemala",
			"Guinea-Bissau",
			"Guinea",
			"Guyana",
			"Haiti",
			"Honduras",
			"Hungary",
			"Iceland",
			"India",
			"Indonesia",
			"Iran  (Islamic Republic of)",
			"Iraq",
			"Ireland",
			"Israel",
			"Italy",
			"Jamaica",
			"Japan",
			"Jordan",
			"Kazakhstan",
			"Kenya",
			"Kiribati",
			"Kuwait",
			"Kyrgyzstan",
			"Lao People's Democratic Republic",
			"Latvia",
			"Lebanon",
			"Lesotho",
			"Liberia",
			"Libyan Arab Jamahiriya",
			"Liechtenstein",
			"Lithuania",
			"Luxembourg",
			"Madagascar",
			"Malawi",
			"Malaysia",
			"Maldives",
			"Mali",
			"Malta",
			"Martinique",
			"Mauritania",
			"Mauritius",
			"Mexico",
			"Moldova, Republic of",
			"Monaco",
			"Mongolia",
			"Montserrat",
			"Morocco",
			"Mozambique",
			"Myanmar",
			"Namibia",
			"Nepal",
			"Netherlands Antilles",
			"Netherlands",
			"New Caledonia",
			"New Zealand",
			"Nicaragua",
			"Niger",
			"Nigeria",
			"Norway",
			"Oman",
			"Pakistan",
			"Panama",
			"Papua New Guinea",
			"Paraguay",
			"Peru",
			"Philippines",
			"Poland",
			"Portugal",
			"Puerto Rico",
			"Qatar",
			"Republic of Korea",
			"Romania",
			"Russian Federation",
			"Rwanda",
			"Saint Kitts and Nevis",
			"Saint Lucia",
			"Saint Vincent and the Grenadines",
			"Samoa",
			"Sao Tome and Principe",
			"Saudi Arabia",
			"Senegal",
			"Seychelles",
			"Sierra Leone",
			"Singapore",
			"Slovakia",
			"Slovenia",
			"Solomon Islands",
			"Somalia",
			"South Africa",
			"Spain",
			"Sri Lanka",
			"Sudan",
			"Suriname",
			"Swaziland",
			"Sweden",
			"Switzerland",
			"Syrian Arab Republic",
			"Tajikistan",
			"Thailand",
			"The former Yugoslav Republic of Macedonia",
			"Timor-Leste",
			"Togo",
			"Tonga",
			"Trinidad and Tobago",
			"Tunisia",
			"Turkey",
			"Turkmenistan",
			"Uganda",
			"Ukraine",
			"United Arab Emirates",
			"U.K. of Great Britain and Northern Ireland",
			"United Republic of Tanzania",
			"United States Virgin Islands",
			"United States of America",
			"Uruguay",
			"Uzbekistan",
			"Vanuatu",
			"Venezuela",
			"Viet Nam",
			"West Bank",
			"Yemen",
			"Zambia",
			"Zimbabwe",
			"Central Africa",
			"Eastern Africa",
			"Northern Africa",
			"Southern Africa",
			"Western Africa",
			"Southern Africa and Great Lakes Countries",
			"European Union",
			"Serbia, Republic of",
			"Gaza Strip",
			"World",
			"Central Asia",
			"Eastern Asia",
			"South-Eastern Asia",
			"Southern Asia",
			"Western Asia",
			"Central America",
			"Northern America",
			"South America"
		};
	
	/**
	 * @deprecated use a centralized class, with gaul codes + labels loaded from db.
	 */
	@Deprecated
	public ListBox fillRegionList(ListBox list) {
		for (int i = 0 ; i < countries.length ; i++)
			list.addItem(countries[i]);
		return list;
	}
	
}
